#!/bin/bash

hosts="laa-slide lab-slide lac-slide lajolla-slide carmel-slide centuryab-slide centurycd-slide marina-slide"

target=${1:-}
if [ "$target" = "" ]; then
  target=.
fi
for host in $hosts; do
  if [ -f $target/$host ]; then
    rm $target/$host
  fi
  ln -s recorder $target/$host
done
