#!/bin/bash

host=`echo $0 | sed 's/\.\///g'`

#hosts="carmel-cam"
#hosts="laa-cam lab-cam lac-cam lajolla-cam carmel-cam centuryab-cam centurycd-cam marina-cam"
LOGDIR=/mnt/big/logs
OUTDIR=/mnt/big/videos

. /lib/lsb/init-functions

CAMAUDIO="camera. ! rtpjitterbuffer  latency=2000 ! rtpg726depay ! decodebin ! queue ! audiorate ! audio/x-raw,rate=8000,channels=1 ! audioconvert ! audioresample ! audio/x-raw,rate=44100,channels=1 "
MCAMAUDIO="camera. ! rtpjitterbuffer latency=2000 ! rtppcmudepay ! decodebin ! queue ! audiorate ! audio/x-raw,rate=8000,channels=1 ! audioconvert ! audioresample ! audio/x-raw,rate=44100,channels=1 ! rgvolume pre-amp=6.0 headroom=10.0 ! rglimiter ! audioconvert "

VIDSRC="camera. ! rtpjitterbuffer  latency=2000 ! rtph264depay ! decodebin ! queue "
VPARSE="h264parse ! \"video/x-h264,level=(string)4.1,profile=main\" ! queue "
AENCODER="voaacenc bitrate=128000"
APARSE="aacparse ! audio/mpeg,mpegversion=4,stream-format=raw ! queue "
MUX="mpegtsmux name=muxer ! queue name=muxed "


checkurl()
{
  curl=`curl -f -s -I http://$1 2> /dev/null`
  retval=$?
  while [ $retval -ne 0 ]; do
    curl=`curl -f -s -I http://$1 2> /dev/null`
    retval=$?
  done
}

proxyvideo()
{
  CAMSRC="rtspsrc location=rtspt://${1}:554/profile3/media.smp latency=2000 name=camera "
  date=`/bin/date +%Y%m%d_%H%M`
  if [ -d "$LOGDIR" ]; then
    mkdir -p $LOGDIR
  fi
  logfile=$LOGDIR/$1
  OUTPUTFILE=${OUTDIR}/${1}_${date}.ts
  echo "###### Started at: $(date) #######" >> ${logfile}.log
  echo "###### Started at: $(date) #######" >> ${logfile}.err
  setsid gst-launch-1.0 \
    $CAMSRC \
    camera. ! rtpjitterbuffer latency=2000 ! rtpmp2tdepay ! queue ! \
    filesink location=$OUTPUTFILE \
    2>> ${logfile}.err >> ${logfile}.log
  echo "###### Exited at: $(date) #######" >> ${logfile}.log
  echo "###### Exited at: $(date) #######" >> ${logfile}.err
}

loopvideo()
{
  while [ true ]; do
    proxyvideo $1
  done
}

stop()
{
  cur=$$
  for pid in $(/usr/bin/pgrep $host); do
    echo "$cur--$pid"
    if [ $pid -ne $cur ] ; then
      kill $pid
    fi
  done
  gst=`/bin/grep [g]st\-launch | /bin/grep $host | awk '{ print $2 }'`
  kill $gst
}

case "$1" in
  start)
	echo -n "starting $host:   "
	loopvideo $host &
	sleep 1
	running=`/bin/ps aux | /bin/grep [g]st\-launch | /bin/grep $host | wc -l`
	if [ $running -eq 1 ] ; then
	  echo "finished."
	else
	  echo "Failed!"
	fi
	;;
  test)
	echo -n "starting $host:   "
	proxyvideo $host &
	sleep 1
	running=`/bin/ps aux | /bin/grep [g]st\-launch | /bin/grep $host | wc -l`
	if [ $running -eq 1 ] ; then
	  echo "finished."
	else
	  echo "Failed!"
	fi
	echo "finished."
	;;
  stop)
	echo -n "stoping $host:   "
	stop
	echo "finished."
	;;
  status)
	app=`/bin/ps aux | /bin/grep [g]st-launch | /bin/grep $host | wc -l`
	if [ $app -eq 1 ] ; then
	  echo "$host Running"
	  exit 0
        else
	  echo "$host not running."
          exit 1
	fi
	;;
  *)
	echo $"Usage: $0 {start|stop|restart|status|capture}"
	exit 1
esac
exit 0

