#!/bin/bash

ident="southern-califo-0973.ew85-q6vj-x5mv-e2zj"
ALSAINPUT=`arecord --list-pcms | grep default | grep CODEC`
V4LINPUT=`v4l2-ctl --list-devices | grep stk1160 -A1 | tail -1 | awk '{ print $1 }'`

gst-launch-1.0 -v videomixer name=mix sink_1::xpos=480 sink_1::ypos=60 ! videoconvert ! "video/x-raw, width=1920, height=1080" ! \
   queue ! videorate ! "video/x-raw,framerate=30/1" ! videoconvert ! videoscale ! "video/x-raw, width=640, height=360" ! x264enc bitrate=768 key-int-max=60 bframes=0 \
     byte-stream=false aud=true tune=zerolatency ! h264parse ! \
     "video/x-h264,level=(string)4.1,profile=main" ! queue ! mux. \
   alsasrc device="$ALSAINPUT" ! "audio/x-raw,format=S16LE,rate=44100,channels=1" ! \
     queue ! voaacenc bitrate=128000 ! \
     aacparse ! "audio/mpeg,mpegversion=4,stream-format=raw" ! queue ! \
   flvmux streamable=true name=mux ! queue ! \
   filesink location=test.flv \
   v4l2src device=$V4LINPUT ! \
     "video/x-raw,format=I420,framerate=30000/1001,width=720,height=480,interlace-mode=mixed,pixel-aspect-ratio=1/1" ! \
     videoscale ! video/x-raw,width=1440,height=960 ! mix. \
   videotestsrc pattern=smpte is-live=true ! video/x-raw,width=1920,height=1080 ! \
     videoscale ! video/x-raw,width=480,height=270,framerate=30/1 ! mix. \
   multifilesrc location="../test-scripts/lax.jpg" caps="image/jpeg,framerate=1/1" ! \
     jpegdec  ! "video/x-raw, width=1920, height=1080" ! mix.

