#!/bin/bash
#first pass a a pipeline to push from SNP-6200 rtsp to gst-switch.

#this test pipe line should provide data from snp-6200 to gst-switch
gst_w=1280
gst_h=720
ipaddress=192.168.2.155
capfile='video.ts'
PUSHIP=192.168.2.226

gst-launch-1.0 -v \
  mpegtsmux name=muxer \
  rtspsrc location=rtspt://${ipaddress}:554/profile3/media.smp latency=0 name=camera is-live=true \
  camera. ! rtph264depay ! tee name=video ! queue ! muxer. \
  camera. ! rtpg726depay ! decodebin ! audioconvert ! \
    audioresample ! "audio/x-raw,rate=44100" ! \
    voaacenc bitrate=128000 ! tee name=audio ! queue ! muxer. \
  video. ! queue ! rtph264pay ! udpsink host=$PUSHIP port=8000 \
  audio. ! queue ! rtpmp4apay ! udpsink host=$PUSHIP port=8001



