#!/bin/bash

host=`echo $0 | sed 's/\.\///g'`
ident=""
#hosts="carmel-cam"
#hosts="laa-cam lab-cam lac-cam lajolla-cam carmel-cam centuryab-cam centurycd-cam marina-cam"
LOGDIR=/mnt/storage/logs
OUTDIR=/mnt/storage/videos

. /lib/lsb/init-functions

CAMAUDIO="camera. ! rtpjitterbuffer  latency=2000 ! rtpg726depay ! decodebin ! queue ! audio/x-raw,rate=8000,channels=1 ! audioconvert ! audioresample ! audio/x-raw,rate=44100,channels=1 "
#CAMAUDIO="camera. ! rtpjitterbuffer  latency=2000 ! rtpg726depay ! decodebin  ! queue ! audiorate ! audio/x-raw,rate=8000,channels=1 ! audioconvert ! audioresample ! audio/x-raw,rate=44100,channels=1 "
#CAMAUDIO="camera. ! rtpjitterbuffer  latency=2000 ! rtpg726depay ! decodebin  ! queue ! audiorate ! audio/x-raw,rate=8000,channels=1 "
#CAMAUDIO="camera. ! rtpjitterbuffer  latency=2000 ! rtpg726depay ! avdec_g726 ! queue ! audiorate ! audio/x-raw,rate=8000,channels=1 ! audioconvert ! audioresample ! audio/x-raw,rate=44100,channels=1 "

CAMVIDEO="camera. ! rtpjitterbuffer  latency=2000 ! rtph264depay "
VPARSE="h264parse ! "video/x-h264,level=(string)4.1,profile=main" ! queue ! muxer. "
AENCODER="voaacenc bitrate=128000"
APARSE="aacparse ! audio/mpeg,mpegversion=4,stream-format=raw ! queue ! muxer. "
MUX="mpegtsmux name=muxer ! queue name=muxed "
MUX2="flvmux streamable=true name=muxer ! queue name=muxed "

checkurl()
{
  curl=`curl -f -s -I http://$1 2> /dev/null`
  retval=$?
  while [ $retval -ne 0 ]; do
    curl=`curl -f -s -I http://$1 2> /dev/null`
    retval=$?
  done
}

startvideo()
{
  date=`/bin/date +%Y%m%d_%H%M`
  OUTPUTFILE=${OUTDIR}/${1}_${date}.flv
  proxyvideo $1 $date $OUTPUTFILE &
  sleep 1
  running=`/bin/ps aux | /bin/grep [g]st\-launch | /bin/grep $host | wc -l`
  if [ $running -eq 1 ] ; then
    sleep 2
    size=`ls -l $OUTPUTFILE | awk '{ print $5 }'`
    echo "\n\n[$size]"
  else
    return false
  fi
}

proxyvideo()
{
  CAMSRC="rtspsrc location=rtsp://${1}:554/profile3/media.smp latency=2000 name=camera "
  date=$2
  OUTPUTFILE=$3
  if [ -d "$LOGDIR" ]; then
    mkdir -p $LOGDIR
  fi
  logfile=$LOGDIR/$1
  if [ -d "$OUTDIR" ]; then
    mkdir -p $OUTDIR
  fi
  echo "###### Started at: $(date) #######" >> ${logfile}.log
  echo "###### Started at: $(date) #######" >> ${logfile}.err

  setsid gst-launch-1.0 \
    $CAMSRC \
    $CAMVIDEO ! $VPARSE \
    $CAMAUDIO ! queue ! $AENCODER ! $APARSE \
    $MUX2 ! filesink location=$OUTPUTFILE \
    2>> ${logfile}.err >> ${logfile}.log
  echo "###### Exited at: $(date) #######" >> ${logfile}.log
  echo "###### Exited at: $(date) #######" >> ${logfile}.err

}

loopvideo()
{
  while [ true ]; do
    proxyvideo $1
  done
}

stop()
{
  cur=$$
  for pid in $(/usr/bin/pgrep $host); do
    if [ $pid -ne $cur ] ; then
      kill $pid
    fi
  done
  for pid in $(ps aux | /bin/grep [g]st\-launch | /bin/grep $host | awk '{ print $2 }'); do
    kill $pid
  done
}

case "$1" in
  start)
	echo -n "starting $host:   "
	loopvideo $host &
	sleep 1
	running=`/bin/ps aux | /bin/grep [g]st\-launch | /bin/grep $host | wc -l`
	if [ $running -eq 1 ] ; then
	  echo "finished."
	else
	  echo "Failed!"
	fi
	;;
  test)
	echo -n "starting $host:   "
	startvideo $host
	sleep 1
	;;
  stop)
	echo -n "stoping $host:   "
	stop 
	echo "finished."
	;;
  status)
	app=`/bin/ps aux | /bin/grep [g]st-launch | /bin/grep $host | wc -l`
	if [ $app -eq 1 ] ; then
	  echo "$host Running"
	  exit 0
        else
	  echo "$host not running."
          exit 1
	fi
	;;
  *)
	echo $"Usage: $0 {start|stop|restart|status|capture}"
	exit 1
esac
exit 0

