#!/bin/bash

ipaddress=192.168.2.155
capfile='video.ts'
ident="southern-califo-0973.ha78-9u9r-yrjp-dypd"

gst-launch-1.0 mpegtsmux name=muxer ! filesink location=${capfile} \
  rtspsrc location=rtspt://${ipaddress}:554/profile3/media.smp \
	latency=0 name=camera \
  camera. ! rtph264depay ! tee name=video ! queue ! muxer. \
  camera. ! rtpg726depay ! avdec_g726 ! audioconvert ! \
    audioresample ! "audio/x-raw,rate=44100" ! voaacenc bitrate=128000 ! \
  aacparse ! "audio/mpeg,mpegversion=4,stream-format=raw" ! tee=audio ! \
  queue ! muxer. \
  video. ! queue ! videoconvert ! \
  videoscale ! "video/x-raw, width=640, height=360" ! \
  x264enc bitrate=768 key-int-max=60 bframes=0 \
     byte-stream=false aud=true tune=zerolatency ! h264parse ! \
     "video/x-h264,level=(string)4.1,profile=main" ! queue ! mux. \
   flvmux streamable=true name=mux ! queue ! \
   rtmpsink \
     location="rtmp://a.rtmp.youtube.com/live2/x/${ident}?videoKeyframeFrequency=1&totalDatarate=896 app=live2 flashVer=\"FME/3.0%20(compatible;%20FMSc%201.0)\" swfUrl=rtmp://a.rtmp.youtube.com/live2" 


