#!/bin/bash
#first pass a a pipeline to push from SNP-6200 rtsp to gst-switch.

#this test pipe line should provide data from snp-6200 to gst-switch
ipaddress=192.168.2.155

gst-launch-1.0 -v rtspsrc location=rtspt://${ipaddress}:554/profile3/media.smp latency=0 name=camera camera. ! rtpjitterbuffer ! rtpjpegdepay ! video/jpeg,height=480,width=720 ! vaapidecode ! queue ! vaapisink camera. ! rtpjitterbuffer ! rtpg726depay ! avdec_g726 ! queue ! alsasink sync=false



