#!/bin/bash
#first pass a a pipeline to push from SNP-6200 rtsp to gst-switch.

#this test pipe line should provide data from snp-6200 to gst-switch
camera=192.168.2.155
slides=192.168.2.202
bgfile=lax.jpg
outputfile=mixed.ts
ident=southern-califo-0973.4pa8-30y7-md82-6jq2
audiobr=128
videobr=10240
totalbr=$((audiobr+videobr))

CAMERA="rtspsrc location=rtspt://${camera}:554/profile3/media.smp \
latency=0 name=camera is-live=true"
AUDIO_PROCESS="camera. ! rtpg726depay ! avdec_g726 ! audio/x-raw, rate=8000, channels=1, format=S16LE, layout=interleaved ! queue name=rawcam_a "
AUDIO_RESAMPLE="audioconvert ! audioresample ! audio/x-raw,rate=44100 ! \
queue name=upsampled_a"
AUDIO_ENCODE="avenc_aac bitrate=${audobr}000 ! aacparse ! audio/mpeg,mpegversion=4,stream-format=raw ! queue name=encoded_a"
CAMERA_PROCESS="camera. ! rtph264depay ! video/x-h264, stream-format=avc, \
alignment=au ! h264parse ! video/x-h264, height=1080, width=1920, \
stream-format=avc, alignment=au, parsed=true ! avdec_h264 ! \
video/x-raw, format=I420, width=1920, height=1080, pixel-aspect-ratio=1/1, \
interlace-mode=progressive, colorimetry=bt709 ! \
queue name=rawcam_v "
CAMERA_PROCESSH="camera. ! rtph264depay ! video/x-h264, stream-format=avc, \
alignment=au ! h264parse ! video/x-h264, height=1080, width=1920, \
stream-format=avc, alignment=au, parsed=true ! vaapidecode ! \
vaapipostproc format=i420 width=480 height=270 ! queue name=rawcam_v "
CAMERA_SCALE="rawcam_v. ! videoconvert ! videoscale ! video/x-raw, width=960, height=540 ! videoconvert ! queue name=scaled_v ! mix."

SLIDES="rtspsrc location=rtspt://${slides}:554/profile3/media.smp \
latency=0 is-live=true name=slides"
SLIDES_PROCESS="slides. ! rtpmp2tdepay ! tsdemux ! mpeg2dec ! video/x-raw, format=I420, width=720, height=480, pixel-aspect-ratio=1/1, interlace-mode=progressive, chroma-site=mpeg2, colorimetry=bt601, framerate=30/1 ! queue name=rawslides"
SLIDES_SCALE="rawslides. ! videoconvert ! videoscale ! video/x-raw, width=1440, height=960 ! videocrop top=42 left=68 right=76 bottom=114 ! videoconvert ! queue name=scaled_slides ! mix."
BACKGROUND="multifilesrc location=${bgfile} caps=image/jpeg,framerate=1/1 ! \
jpegdec ! queue name=background ! mix. "


#MUXER="flvmux streamable=true name=muxer"
MUXER="mpegtsmux name=muxer"

RTMPSINK="rtmpsink \
location=\"rtmp://a.rtmp.youtube.com/live2/x/${ident}?videoKeyframeFrequency=1&totalDatarate=$totalbr app=live2 flashVer=\"FME/3.0%20(compatible;%20FMSc%201.0)\" swfUrl=rtmp://a.rtmp.youtube.com/live2\""


gst-launch-1.0 -v \
  $CAMERA \
  $AUDIO_PROCESS \
  rawcam_a. ! $AUDIO_RESAMPLE \
  $CAMERA_PROCESS \
  videomixer name=mix sink_2::xpos=624 sink_2::ypos=282 ! "video/x-raw, width=1920, height=1080, framerate=30/1" ! queue name=rawvideo \
  $BACKGROUND \
  $CAMERA_SCALE \
  $SLIDES \
  $SLIDES_PROCESS \
  $SLIDES_SCALE \
  $MUXER ! \
  filesink location=$outputfile \
  rawvideo. ! x264enc bitrate=$videobr ! h264parse ! \
     "video/x-h264,level=(string)4.1,profile=main" ! queue name=encoded_v ! muxer. \
  upsampled_a. ! $AUDIO_ENCODE ! muxer.
  #rawcam_a. ! muxer.
  #rawvideo. ! autovideosink \
  #rawcam_a. ! alsasink sync=false
exit
#  $SLIDES \
#  $SLIDES_PROCESS \
#  $SLIDES_SCALE \
