#!/bin/bash

gst-launch-1.0 -v udpsrc port=5000 ! "application/x-rtp,media=video,clock-rate=90000,encoding-name=JPEG,payload=96" ! rtpjitterbuffer ! rtpjpegdepay ! queue ! decodebin ! videoconvert ! videoscale ! autovideosink

