#!/bin/bash
#first pass a a pipeline to push from SNP-6200 rtsp to gst-switch.

#this test pipe line should provide data from snp-6200 to gst-switch
ipaddress=192.168.2.202

gst-launch-1.0 -v \
  rtspsrc location=rtspt://${ipaddress}:554/profile3/media.smp \
    latency=0 name=camera \
  camera.! rtpmp2tdepay ! tsdemux ! decodebin ! queue ! \
  fpsdisplaysink
  #autovideosink




