#!/bin/bash

hosts="carmel"
#hosts="laa lab lac lajolla carmel belair centurya centuryb centuryc centuryd marina"

. /lib/lsb/init-functions

CAMAUDIO="camera. ! rtpjitterbuffer  latency=2000 ! rtpg726depay ! decodebin ! queue ! audiorate ! audio/x-raw,rate=8000,channels=1 ! audioconvert ! audioresample ! audio/x-raw,rate=44100,channels=1 "
MCAMAUDIO="camera. ! rtpjitterbuffer latency=2000 ! rtppcmudepay ! decodebin ! queue ! audiorate ! audio/x-raw,rate=8000,channels=1 ! audioconvert ! audioresample ! audio/x-raw,rate=44100,channels=1 ! rgvolume pre-amp=6.0 headroom=10.0 ! rglimiter ! audioconvert "
TESTAUDIO="audiotestsrc wave= is-live=true ! audio/x-raw,rate=8000,channels=1 ! audioconvert ! audioresample ! audio/x-raw,rate=44100,channels=1 "

AUDIOSRC="$CAMAUDIO "

VIDSRC="camera. ! rtpjitterbuffer  latency=2000 ! rtph264depay ! decodebin ! queue "
VPARSE="h264parse ! "video/x-h264,level=(string)4.1,profile=main" ! queue ! muxer. "
AENCODER="voaacenc bitrate=128000"
APARSE="aacparse ! audio/mpeg,mpegversion=4,stream-format=raw ! queue "
MUX="flvmux streamable=true name=muxer ! queue name=muxed "
LOGDIR=./

source idents

checkurl()
{
  curl=`curl -f -s -I http://$1 2> /dev/null`
  retval=$?
  while [ $retval -ne 0 ]; do
    curl=`curl -f -s -I http://$1 2> /dev/null`
    retval=$?
  done
}

proxyvideo()
{
  CAMSRC="rtspsrc location=rtspt://${1}-cam:554/profile5/media.smp latency=2000 name=camera "
  date=`/bin/date +%Y%m%d_%H%M`
  if [ -d "$LOGDIR" ]; then
    mkdir -p $LOGDIR
  fi
  logfile=$LOGDIR/$1
  ident=$1_ident
  echo "###### Started at: $(date) #######" >> ${logfile}.log
  echo "###### Started at: $(date) #######" >> ${logfile}.err
  setsid gst-launch-1.0 \
    $CAMSRC \
    camera. ! rtpjitterbuffer latency=2000 ! rtph264depay ! $VPARSE \
    $MCAMAUDIO ! queue ! \
    $AENCODER ! $APARSE ! $MUX ! \
    rtmpsink \
      location="rtmp://a.rtmp.youtube.com/live2/x/${!ident}?videoKeyframeFrequency=1&totalDatarate=1152 app=live2 flashVer=\"FME/3.0%20(compatible;%20FMSc%201.0)\" swfUrl=rtmp://a.rtmp.youtube.com/live2" \
    2>> ${logfile}.err >> ${logfile}.log
  echo "###### Exited at: $(date) #######" >> ${logfile}.log
  echo "###### Exited at: $(date) #######" >> ${logfile}.err
 
}

loopvideo()
{
  while [ true ]; do
    proxyvideo $1
  done
}

stop()
{
  cur=$$
  for pid in $(/usr/bin/pgrep proxycap); do
    if [ $pid -ne $cur ] ; then
      kill $pid
    fi
  done
  vlc=`/usr/bin/pgrep vlc | wc -l`
  if [ $vlc -gt 0 ]; then
    child=`/usr/bin/killall vlc`
  fi
}

case "$1" in
  start)
	stop
	echo "starting $0   "
	for host in $hosts ; do
	  echo -n "starting $host:   "
	  loopvideo $host &
	  sleep 1
          ident=${host}_ident
	  runningp=`/bin/ps aux | /bin/grep [g]st-launch | /bin/grep ${!ident} | wc -l`
	  if [ $running -eq 1 ] ; then
	    echo "finished."
	  else
	    echo "Failed!"
	  fi
	done 
	;;
  test)
	echo -n "test $0:   "
	proxyvideo carmel &
	echo "finished."
	;;
  stop)
	echo -n "stoping $0:   "
	stop
	echo "finished."
	;;
  status)
	for host in $hosts ; do
          ident=${host}_ident
	  app=`/bin/ps aux | /bin/grep [g]st-launch | /bin/grep ${!ident} | wc -l`
	  if [ $app -eq 1 ] ; then
	    echo "$host Running"
	    exit 0
          else
	    echo "$host not running."
            exit 1
	  fi
	done
	;;
  *)
	echo $"Usage: $0 {start|stop|restart|status|capture}"
	exit 1
esac
exit 0

