#!/bin/bash

HENCODE="vaapiencode_h264 bitrate=$VBR keyframe-period=60 max-bframes=0 "
SENCODE="x264enc bitrate=$VBR key-int-max=60 bframes=0 "

ENCODE="videorate ! video/x-raw,width=640,height=360,framerate=30/1 ! ${SENCODE} "
CAMAUDIO="camera. ! rtpg726depay ! decodebin ! \
audioconvert ! audioresample ! audio/x-raw,rate=44100,channels=1 "
TESTAUDIO="audiotestsrc wave=silence is-live=true ! audio/x-raw,format=S16LE,\
endianness=1234,signed=true,width=16,depth=16,rate=44100,channels=1"

AUDIOSRC="$CAMAUDIO ! mix. $TESTAUDIO ! liveadder name=mix ! \
audio/x-raw,rate=44100,channels=1 ! audiorate "

CAMSRC="rtspsrc location=rtspt://${ipaddress}:554/profile5/media.smp \
latency=0 name=camera do-timestamp=true is-live=true "
VIDSRC="camera. ! rtph264depay ! decodebin ! queue "
VPARSE="h264parse ! "video/x-h264,level=(string)4.1,profile=main" ! \
queue ! muxer. "
AENCODER="voaacenc bitrate=128000"
APARSE="aacparse ! audio/mpeg,mpegversion=4,stream-format=raw ! queue "
MUX="flvmux streamable=true name=muxer ! queue name=muxed "

