#!/bin/bash

ident="southern-califo-0973.ew85-q6vj-x5mv-e2zj"
ipaddress=192.168.2.155
VBR=768

source parts

#while [ true ]
#do
  GST_DEBUG=rtmpsink:5 gst-launch-1.0 -v \
    $CAMSRC \
    $VIDSRC ! $SENCODE  ! $VPARSE \
    $MCAMAUDIO ! queue ! \
    $AENCODER ! $APARSE ! $MUX ! \
    rtmpsink \
      location="rtmp://a.rtmp.youtube.com/live2/x/${ident}?videoKeyframeFrequency=1&totalDatarate=896 app=live2 flashVer=\"FME/3.0%20(compatible;%20FMSc%201.0)\" swfUrl=rtmp://a.rtmp.youtube.com/live2" 
#done
